"""
Device event type definitions for trigger/clear correlation.

Ported from https://github.com/tmunzer/mist_library scripts/reports/list_open_events.py.
Each Mist event type string maps to (category, role, sub_id_field):
- category: groups related trigger/clear events
- role: "trigger" or "clear"
- sub_id_field: how to extract a sub-identifier from the event, or None
  - Direct field name (e.g., "port_id") → event.get(field)
  - "text:<keyword>" → parse from event text after the keyword
"""

# Maps every known Mist event type string → (category, role, sub_id_field)
EVENT_TYPE_MAP: dict[str, tuple[str, str, str | None]] = {
    # ── AP Events ──
    "AP_CONFIG_FAILED":     ("AP_CONFIG", "trigger", None),
    "AP_CONFIGURED":        ("AP_CONFIG", "clear", None),
    "AP_RECONFIGURED":      ("AP_CONFIG", "clear", None),
    "AP_DISCONNECTED":      ("AP_DISCONNECTED", "trigger", None),
    "AP_CONNECTED":         ("AP_DISCONNECTED", "clear", None),
    "AP_PORT_DOWN":         ("AP_PORT", "trigger", "port_id"),
    "AP_PORT_UP":           ("AP_PORT", "clear", "port_id"),
    "AP_RADSEC_FAILURE":    ("AP_RADSEC", "trigger", None),
    "AP_RADSEC_RECOVERY":   ("AP_RADSEC", "clear", None),
    "AP_UPGRADE_FAILED":    ("AP_UPGRADE", "trigger", None),
    "AP_UPGRADED":          ("AP_UPGRADE", "clear", None),
    # ── ESL Events ──
    "ESL_HUNG":             ("ESL_HUNG", "trigger", None),
    "ESL_RECOVERED":        ("ESL_HUNG", "clear", None),
    # ── Gateway Events ──
    "GW_ALARM_CHASSIS_FAN":                 ("GW_ALARM_CHASSIS_FAN", "trigger", None),
    "GW_ALARM_CHASSIS_FAN_CLEAR":           ("GW_ALARM_CHASSIS_FAN", "clear", None),
    "GW_ALARM_CHASSIS_HOT":                 ("GW_ALARM_CHASSIS_HOT", "trigger", None),
    "GW_ALARM_CHASSIS_HOT_CLEAR":           ("GW_ALARM_CHASSIS_HOT", "clear", None),
    "GW_ALARM_CHASSIS_HUMIDITY":            ("GW_ALARM_CHASSIS_HUMIDITY", "trigger", None),
    "GW_ALARM_CHASSIS_HUMIDITY_CLEAR":      ("GW_ALARM_CHASSIS_HUMIDITY", "clear", None),
    "GW_ALARM_CHASSIS_MGMT_LINK_DOWN":      ("GW_ALARM_CHASSIS_MGMT_LINK", "trigger", None),
    "GW_ALARM_CHASSIS_MGMT_LINK_DOWN_CLEAR": ("GW_ALARM_CHASSIS_MGMT_LINK", "clear", None),
    "GW_ALARM_CHASSIS_PARTITION":           ("GW_ALARM_CHASSIS_PARTITION", "trigger", None),
    "GW_ALARM_CHASSIS_PARTITION_CLEAR":     ("GW_ALARM_CHASSIS_PARTITION", "clear", None),
    "GW_ALARM_CHASSIS_PEM":                 ("GW_ALARM_CHASSIS_PEM", "trigger", None),
    "GW_ALARM_CHASSIS_PEM_CLEAR":           ("GW_ALARM_CHASSIS_PEM", "clear", None),
    "GW_ALARM_CHASSIS_POE":                 ("GW_ALARM_CHASSIS_POE", "trigger", None),
    "GW_ALARM_CHASSIS_POE_CLEAR":           ("GW_ALARM_CHASSIS_POE", "clear", None),
    "GW_ALARM_CHASSIS_PSU":                 ("GW_ALARM_CHASSIS_PSU", "trigger", None),
    "GW_ALARM_CHASSIS_PSU_CLEAR":           ("GW_ALARM_CHASSIS_PSU", "clear", None),
    "GW_ALARM_CHASSIS_WARM":                ("GW_ALARM_CHASSIS_WARM", "trigger", None),
    "GW_ALARM_CHASSIS_WARM_CLEAR":          ("GW_ALARM_CHASSIS_WARM", "clear", None),
    "GW_APPID_INSTALL_FAILED":              ("GW_APPID_INSTALL", "trigger", None),
    "GW_APPID_INSTALLED":                   ("GW_APPID_INSTALL", "clear", None),
    "GW_ARP_UNRESOLVED":    ("GW_ARP", "trigger", "port_id"),
    "GW_ARP_RESOLVED":      ("GW_ARP", "clear", "port_id"),
    "GW_BGP_NEIGHBOR_DOWN": ("GW_BGP_NEIGHBOR", "trigger", "text:neighbor"),
    "GW_BGP_NEIGHBOR_UP":   ("GW_BGP_NEIGHBOR", "clear", "text:neighbor"),
    "GW_CONDUCTOR_DISCONNECTED": ("GW_CONDUCTOR", "trigger", None),
    "GW_CONDUCTOR_CONNECTED":    ("GW_CONDUCTOR", "clear", None),
    "GW_CONFIG_FAILED":             ("GW_CONFIG", "trigger", None),
    "GW_CONFIG_LOCK_FAILED":        ("GW_CONFIG", "trigger", None),
    "GW_CONFIG_ERROR_ADDTL_COMMAND": ("GW_CONFIG", "trigger", None),
    "GW_CONFIGURED":                ("GW_CONFIG", "clear", None),
    "GW_RECONFIGURED":              ("GW_CONFIG", "clear", None),
    "GW_DHCP_UNRESOLVED":  ("GW_DHCP", "trigger", None),
    "GW_DHCP_RESOLVED":    ("GW_DHCP", "clear", None),
    "GW_DISCONNECTED":     ("GW_DISCONNECTED", "trigger", None),
    "GW_CONNECTED":        ("GW_DISCONNECTED", "clear", None),
    "GW_FIB_COUNT_THRESHOLD_EXCEEDED":    ("GW_FIB_COUNT", "trigger", None),
    "GW_FIB_COUNT_RETURNED_TO_NORMAL":    ("GW_FIB_COUNT", "clear", None),
    "GW_FLOW_COUNT_THRESHOLD_EXCEEDED":   ("GW_FLOW_COUNT", "trigger", None),
    "GW_FLOW_COUNT_RETURNED_TO_NORMAL":   ("GW_FLOW_COUNT", "clear", None),
    "GW_HA_CONTROL_LINK_DOWN":            ("GW_HA_CONTROL_LINK", "trigger", None),
    "GW_HA_CONTROL_LINK_UP":              ("GW_HA_CONTROL_LINK", "clear", None),
    "GW_HA_HEALTH_WEIGHT_LOW":            ("GW_HA_HEALTH_WEIGHT", "trigger", "text:Detected"),
    "GW_HA_HEALTH_WEIGHT_RECOVERY":       ("GW_HA_HEALTH_WEIGHT", "clear", "text:Detected"),
    "GW_IDP_INSTALL_FAILED":              ("GW_IDP_INSTALL", "trigger", None),
    "GW_IDP_INSTALLED":                   ("GW_IDP_INSTALL", "clear", None),
    "GW_OSPF_NEIGHBOR_DOWN": ("GW_OSPF_NEIGHBOR", "trigger", "text:neighbor"),
    "GW_OSPF_NEIGHBOR_UP":   ("GW_OSPF_NEIGHBOR", "clear", "text:neighbor"),
    "GW_PORT_DOWN":         ("GW_PORT", "trigger", "port_id"),
    "GW_PORT_UP":           ("GW_PORT", "clear", "port_id"),
    "GW_RECOVERY_SNAPSHOT_FAILED":      ("GW_RECOVERY_SNAPSHOT", "trigger", None),
    "GW_RECOVERY_SNAPSHOT_SUCCEEDED":   ("GW_RECOVERY_SNAPSHOT", "clear", None),
    "GW_RECOVERY_SNAPSHOT_NOTNEEDED":   ("GW_RECOVERY_SNAPSHOT", "clear", None),
    "GW_TUNNEL_DOWN":       ("GW_TUNNEL", "trigger", "text:Tunnel"),
    "GW_TUNNEL_UP":         ("GW_TUNNEL", "clear", "text:Tunnel"),
    "GW_UPGRADE_FAILED":    ("GW_UPGRADE", "trigger", None),
    "GW_UPGRADED":          ("GW_UPGRADE", "clear", None),
    "GW_VPN_PATH_DOWN":     ("GW_VPN_PATH", "trigger", "text:path"),
    "GW_VPN_PATH_UP":       ("GW_VPN_PATH", "clear", "text:path"),
    "GW_VPN_PEER_DOWN":     ("GW_VPN_PEER", "trigger", "text:peer"),
    "GW_VPN_PEER_UP":       ("GW_VPN_PEER", "clear", "text:peer"),
    "GW_ZTP_FAILED":        ("GW_ZTP", "trigger", None),
    "GW_ZTP_FINISHED":      ("GW_ZTP", "clear", None),
    # ── MX Edge Events ──
    "ME_DISCONNECTED":              ("ME_DISCONNECTED", "trigger", None),
    "ME_CONNECTED":                 ("ME_DISCONNECTED", "clear", None),
    "ME_FAN_UNPLUGGED":             ("ME_FAN", "trigger", "component"),
    "ME_FAN_PLUGGED":               ("ME_FAN", "clear", "component"),
    "ME_POWERINPUT_DISCONNECTED":   ("ME_POWERINPUT", "trigger", "component"),
    "ME_POWERINPUT_CONNECTED":      ("ME_POWERINPUT", "clear", "component"),
    "ME_PSU_UNPLUGGED":             ("ME_PSU", "trigger", "component"),
    "ME_PSU_PLUGGED":               ("ME_PSU", "clear", "component"),
    "ME_SERVICE_CRASHED":           ("ME_SERVICE", "trigger", "service"),
    "ME_SERVICE_FAILED":            ("ME_SERVICE", "trigger", "service"),
    "ME_SERVICE_STARTED":           ("ME_SERVICE", "clear", "service"),
    # ── Switch Events ──
    "SW_ALARM_CHASSIS_FAN":                 ("SW_ALARM_CHASSIS_FAN", "trigger", None),
    "SW_ALARM_CHASSIS_FAN_CLEAR":           ("SW_ALARM_CHASSIS_FAN", "clear", None),
    "SW_ALARM_CHASSIS_HOT":                 ("SW_ALARM_CHASSIS_HOT", "trigger", None),
    "SW_ALARM_CHASSIS_HOT_CLEAR":           ("SW_ALARM_CHASSIS_HOT", "clear", None),
    "SW_ALARM_CHASSIS_HUMIDITY":            ("SW_ALARM_CHASSIS_HUMIDITY", "trigger", None),
    "SW_ALARM_CHASSIS_HUMIDITY_CLEAR":      ("SW_ALARM_CHASSIS_HUMIDITY", "clear", None),
    "SW_ALARM_CHASSIS_MGMT_LINK_DOWN":      ("SW_ALARM_CHASSIS_MGMT_LINK", "trigger", None),
    "SW_ALARM_CHASSIS_MGMT_LINK_DOWN_CLEAR": ("SW_ALARM_CHASSIS_MGMT_LINK", "clear", None),
    "SW_ALARM_CHASSIS_PARTITION":           ("SW_ALARM_CHASSIS_PARTITION", "trigger", None),
    "SW_ALARM_CHASSIS_PARTITION_CLEAR":     ("SW_ALARM_CHASSIS_PARTITION", "clear", None),
    "SW_ALARM_CHASSIS_PEM":                 ("SW_ALARM_CHASSIS_PEM", "trigger", None),
    "SW_ALARM_CHASSIS_PEM_CLEAR":           ("SW_ALARM_CHASSIS_PEM", "clear", None),
    "SW_ALARM_CHASSIS_POE":                 ("SW_ALARM_CHASSIS_POE", "trigger", None),
    "SW_ALARM_CHASSIS_POE_CLEAR":           ("SW_ALARM_CHASSIS_POE", "clear", None),
    "SW_ALARM_CHASSIS_PSU":                 ("SW_ALARM_CHASSIS_PSU", "trigger", None),
    "SW_ALARM_CHASSIS_PSU_CLEAR":           ("SW_ALARM_CHASSIS_PSU", "clear", None),
    "SW_ALARM_IOT_SET":                     ("SW_ALARM_IOT", "trigger", None),
    "SW_ALARM_IOT_CLEAR":                   ("SW_ALARM_IOT", "clear", None),
    "SW_ALARM_VIRTUAL_CHASSIS_VERSION_MISMATCH":       ("SW_ALARM_VC_VERSION_MISMATCH", "trigger", None),
    "SW_ALARM_VIRTUAL_CHASSIS_VERSION_MISMATCH_CLEAR": ("SW_ALARM_VC_VERSION_MISMATCH", "clear", None),
    "SW_BFD_SESSION_DISCONNECTED":  ("SW_BFD_SESSION", "trigger", None),
    "SW_BFD_SESSION_ESTABLISHED":   ("SW_BFD_SESSION", "clear", None),
    "SW_BGP_NEIGHBOR_DOWN": ("SW_BGP_NEIGHBOR", "trigger", "text:neighbor"),
    "SW_BGP_NEIGHBOR_UP":   ("SW_BGP_NEIGHBOR", "clear", "text:neighbor"),
    "SW_CONFIG_FAILED":             ("SW_CONFIG", "trigger", None),
    "SW_CONFIG_LOCK_FAILED":        ("SW_CONFIG", "trigger", None),
    "SW_CONFIG_ERROR_ADDTL_COMMAND": ("SW_CONFIG", "trigger", None),
    "SW_CONFIGURED":                ("SW_CONFIG", "clear", None),
    "SW_RECONFIGURED":              ("SW_CONFIG", "clear", None),
    "SW_DDOS_PROTOCOL_VIOLATION_SET":   ("SW_DDOS_PROTOCOL_VIOLATION", "trigger", "protocol_name"),
    "SW_DDOS_PROTOCOL_VIOLATION_CLEAR": ("SW_DDOS_PROTOCOL_VIOLATION", "clear", "protocol_name"),
    "SW_DISCONNECTED":      ("SW_DISCONNECTED", "trigger", None),
    "SW_CONNECTED":         ("SW_DISCONNECTED", "clear", None),
    "SW_EVPN_CORE_ISOLATED":           ("SW_EVPN_CORE_ISOLATION", "trigger", None),
    "SW_EVPN_CORE_ISOLATION_CLEARED":  ("SW_EVPN_CORE_ISOLATION", "clear", None),
    "SW_FPC_POWER_OFF":     ("SW_FPC_POWER", "trigger", "fru_slot"),
    "SW_FPC_POWER_ON":      ("SW_FPC_POWER", "clear", "fru_slot"),
    "SW_LACPD_TIMEOUT":             ("SW_LACPD_TIMEOUT", "trigger", "port_id"),
    "SW_LACPD_TIMEOUT_CLEARED":     ("SW_LACPD_TIMEOUT", "clear", "port_id"),
    "SW_LOOP_DETECTED":     ("SW_LOOP", "trigger", None),
    "SW_LOOP_CLEARED":      ("SW_LOOP", "clear", None),
    "SW_MAC_LEARNING_STOPPED":  ("SW_MAC_LEARNING", "trigger", None),
    "SW_MAC_LEARNING_RESUMED":  ("SW_MAC_LEARNING", "clear", None),
    "SW_MAC_LIMIT_EXCEEDED": ("SW_MAC_LIMIT", "trigger", "port_id"),
    "SW_MAC_LIMIT_RESET":   ("SW_MAC_LIMIT", "clear", "port_id"),
    "SW_OSPF_NEIGHBOR_DOWN": ("SW_OSPF_NEIGHBOR", "trigger", "text:neighbor"),
    "SW_OSPF_NEIGHBOR_UP":   ("SW_OSPF_NEIGHBOR", "clear", "text:neighbor"),
    "SW_PORT_DOWN":         ("SW_PORT", "trigger", "port_id"),
    "SW_PORT_UP":           ("SW_PORT", "clear", "port_id"),
    "SW_PORT_BPDU_BLOCKED":        ("SW_PORT_BPDU", "trigger", "port_id"),
    "SW_PORT_BPDU_ERROR_CLEARED":  ("SW_PORT_BPDU", "clear", "port_id"),
    "SW_RECOVERY_SNAPSHOT_FAILED":      ("SW_RECOVERY_SNAPSHOT", "trigger", None),
    "SW_RECOVERY_SNAPSHOT_SUCCEEDED":   ("SW_RECOVERY_SNAPSHOT", "clear", None),
    "SW_RECOVERY_SNAPSHOT_NOTNEEDED":   ("SW_RECOVERY_SNAPSHOT", "clear", None),
    "SW_UPGRADE_FAILED":    ("SW_UPGRADE", "trigger", None),
    "SW_UPGRADED":          ("SW_UPGRADE", "clear", None),
    "SW_VC_PORT_DOWN":      ("SW_VC_PORT", "trigger", "port_id"),
    "SW_VC_PORT_UP":        ("SW_VC_PORT", "clear", "port_id"),
    "SW_VC_IN_TRANSITION":  ("SW_VC_TRANSITION", "trigger", None),
    "SW_VC_STABLE":         ("SW_VC_TRANSITION", "clear", None),
    "SW_ZTP_FAILED":        ("SW_ZTP", "trigger", None),
    "SW_ZTP_FINISHED":      ("SW_ZTP", "clear", None),
    # ── TunTerm Events ──
    "TT_MONITORED_RESOURCE_FAILED":     ("TT_MONITORED_RESOURCE", "trigger", "resource"),
    "TT_MONITORED_RESOURCE_RECOVERED":  ("TT_MONITORED_RESOURCE", "clear", "resource"),
    "TT_PORT_BLOCKED":      ("TT_PORT_BLOCKED", "trigger", "port"),
    "TT_PORT_RECOVERY":     ("TT_PORT_BLOCKED", "clear", "port"),
    "TT_PORT_DROPPED_FROM_LACP":        ("TT_PORT_LACP", "trigger", "port"),
    "TT_PORT_LAST_DROPPED_FROM_LACP":   ("TT_PORT_LACP", "trigger", "port"),
    "TT_PORT_JOINED_LACP":              ("TT_PORT_LACP", "clear", "port"),
    "TT_PORT_FIRST_JOIN_LACP":          ("TT_PORT_LACP", "clear", "port"),
    "TT_PORT_LINK_DOWN":    ("TT_PORT_LINK", "trigger", "port"),
    "TT_PORT_LINK_RECOVERY": ("TT_PORT_LINK", "clear", "port"),
    "TT_TUNNELS_LOST":      ("TT_TUNNELS", "trigger", None),
    "TT_TUNNELS_UP":        ("TT_TUNNELS", "clear", None),
}

# Human-readable display names for event categories
EVENT_CATEGORY_DISPLAY: dict[str, str] = {
    # AP
    "AP_CONFIG":        "AP Config Failed",
    "AP_DISCONNECTED":  "AP Disconnected",
    "AP_PORT":          "AP Port Down",
    "AP_RADSEC":        "AP RADSEC Failure",
    "AP_UPGRADE":       "AP Upgrade Failed",
    # ESL
    "ESL_HUNG":         "ESL Hung",
    # Gateway
    "GW_ALARM_CHASSIS_FAN":       "GW Chassis Fan Alarm",
    "GW_ALARM_CHASSIS_HOT":       "GW Chassis Hot Alarm",
    "GW_ALARM_CHASSIS_HUMIDITY":  "GW Chassis Humidity Alarm",
    "GW_ALARM_CHASSIS_MGMT_LINK": "GW Chassis Mgmt Link Down",
    "GW_ALARM_CHASSIS_PARTITION": "GW Chassis Partition Alarm",
    "GW_ALARM_CHASSIS_PEM":       "GW Chassis PEM Alarm",
    "GW_ALARM_CHASSIS_POE":       "GW Chassis PoE Alarm",
    "GW_ALARM_CHASSIS_PSU":       "GW Chassis PSU Alarm",
    "GW_ALARM_CHASSIS_WARM":      "GW Chassis Warm Alarm",
    "GW_APPID_INSTALL":   "GW AppID Install Failed",
    "GW_ARP":             "GW ARP Unresolved",
    "GW_BGP_NEIGHBOR":    "GW BGP Neighbor Down",
    "GW_CONDUCTOR":       "GW Conductor Disconnected",
    "GW_CONFIG":          "GW Config Failed",
    "GW_DHCP":            "GW DHCP Unresolved",
    "GW_DISCONNECTED":    "GW Disconnected",
    "GW_FIB_COUNT":       "GW FIB Count Exceeded",
    "GW_FLOW_COUNT":      "GW Flow Count Exceeded",
    "GW_HA_CONTROL_LINK": "GW HA Control Link Down",
    "GW_HA_HEALTH_WEIGHT": "GW HA Health Weight Low",
    "GW_IDP_INSTALL":     "GW IDP Install Failed",
    "GW_OSPF_NEIGHBOR":   "GW OSPF Neighbor Down",
    "GW_PORT":            "GW Port Down",
    "GW_RECOVERY_SNAPSHOT": "GW Recovery Snapshot Failed",
    "GW_TUNNEL":          "GW Tunnel Down",
    "GW_UPGRADE":         "GW Upgrade Failed",
    "GW_VPN_PATH":        "GW VPN Path Down",
    "GW_VPN_PEER":        "GW VPN Peer Down",
    "GW_ZTP":             "GW ZTP Failed",
    # MX Edge
    "ME_DISCONNECTED":    "MX Edge Disconnected",
    "ME_FAN":             "MX Edge Fan Unplugged",
    "ME_POWERINPUT":      "MX Edge Power Input Disconnected",
    "ME_PSU":             "MX Edge PSU Unplugged",
    "ME_SERVICE":         "MX Edge Service Failed",
    # Switch
    "SW_ALARM_CHASSIS_FAN":       "SW Chassis Fan Alarm",
    "SW_ALARM_CHASSIS_HOT":       "SW Chassis Hot Alarm",
    "SW_ALARM_CHASSIS_HUMIDITY":  "SW Chassis Humidity Alarm",
    "SW_ALARM_CHASSIS_MGMT_LINK": "SW Chassis Mgmt Link Down",
    "SW_ALARM_CHASSIS_PARTITION": "SW Chassis Partition Alarm",
    "SW_ALARM_CHASSIS_PEM":       "SW Chassis PEM Alarm",
    "SW_ALARM_CHASSIS_POE":       "SW Chassis PoE Alarm",
    "SW_ALARM_CHASSIS_PSU":       "SW Chassis PSU Alarm",
    "SW_ALARM_IOT":               "SW IoT Alarm",
    "SW_ALARM_VC_VERSION_MISMATCH": "SW VC Version Mismatch",
    "SW_BFD_SESSION":     "SW BFD Session Down",
    "SW_BGP_NEIGHBOR":    "SW BGP Neighbor Down",
    "SW_CONFIG":          "SW Config Failed",
    "SW_DDOS_PROTOCOL_VIOLATION": "SW DDoS Protocol Violation",
    "SW_DISCONNECTED":    "SW Disconnected",
    "SW_EVPN_CORE_ISOLATION": "SW EVPN Core Isolated",
    "SW_FPC_POWER":       "SW FPC Power Off",
    "SW_LACPD_TIMEOUT":   "SW LACP Timeout",
    "SW_LOOP":            "SW Loop Detected",
    "SW_MAC_LEARNING":    "SW MAC Learning Stopped",
    "SW_MAC_LIMIT":       "SW MAC Limit Exceeded",
    "SW_OSPF_NEIGHBOR":   "SW OSPF Neighbor Down",
    "SW_PORT":            "SW Port Down",
    "SW_PORT_BPDU":       "SW Port BPDU Blocked",
    "SW_RECOVERY_SNAPSHOT": "SW Recovery Snapshot Failed",
    "SW_UPGRADE":         "SW Upgrade Failed",
    "SW_VC_PORT":         "SW VC Port Down",
    "SW_VC_TRANSITION":   "SW VC In Transition",
    "SW_ZTP":             "SW ZTP Failed",
    # TunTerm
    "TT_MONITORED_RESOURCE": "TT Monitored Resource Failed",
    "TT_PORT_BLOCKED":    "TT Port Blocked",
    "TT_PORT_LACP":       "TT Port Dropped from LACP",
    "TT_PORT_LINK":       "TT Port Link Down",
    "TT_TUNNELS":         "TT Tunnels Lost",
}


def extract_sub_id(event: dict, sub_id_field: str | None) -> str:
    """Extract a sub-identifier from a device event.

    Supports:
    - None → returns ""
    - "field_name" → event.get(field_name, "")
    - "text:keyword" → parse word after keyword from event text
    """
    if not sub_id_field:
        return ""

    if sub_id_field.startswith("text:"):
        keyword = sub_id_field[5:]
        text = event.get("text", "")
        try:
            return text.split(keyword)[1].strip().split(" ")[0].rstrip(",").rstrip(".")
        except (IndexError, AttributeError):
            return ""

    return str(event.get(sub_id_field, "") or "")
